services:
  modbus2prometheus:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: modbus2prometheus
    volumes:
      - /etc/modbus2prometheus.config.yaml:/app/config.yaml:ro
    command: ["./modbus2prometheus", "-config", "/app/config.yaml"]
    restart: unless-stopped
    networks:
      - proxy

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   volumes:
  #     - ./grafana.ini:/etc/grafana/grafana.ini:ro
  #   restart: unless-stopped
  #   networks:
  #     - proxy

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - modbus2prometheus
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
