upstream modbus2prometheus {
    server 127.0.0.1:9101;
}

upstream grafana {
    server 127.0.0.1:3000;
}

upstream nodered {
    server 127.0.0.1:1880;
}

upstream zigbee2mqtt {
    server 127.0.0.1:8080;
}

upstream victoria {
    server 127.0.0.1:8428;
}

server {
    listen 80;
    server_name _;

    location = / {                                                                                                                                                     
      rewrite ^ /grafana/d/eb875f21-0c9f-4934-92ba-1ea96c066e3e/otoplenie-doma?var-avg_interval=5m&orgId=1&from=now-6h&to=now&timezone=browser&refresh=30m redirect; 
    } 

    location /modbus2prometheus/ {
        proxy_pass http://modbus2prometheus/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /victoria/ {
        proxy_pass http://victoria/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /zigbee2mqtt/ {
        proxy_pass http://zigbee2mqtt/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /grafana/ {
        proxy_pass http://grafana/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 80;
        proxy_redirect / /grafana/;
    }

    location /nodered/ {
        proxy_pass http://nodered/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /dashboard/ {
        proxy_pass http://nodered/dashboard/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
