name: Generate release-artifacts

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build_release:
    name: Generate cross-platform release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify
        run: |
          test -z "$(gofmt -l .)"
          go test -race ./... -count=1
          go vet ./...

      - name: Build for arm
        run: GOOS=linux GOARCH=arm go build -o modbus2prometheus .

      - name: Gzip for arm
        run: tar -czf modbus2prometheus-linux-arm.tar.gz modbus2prometheus

      - name: Upload Linux ARM artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./modbus2prometheus-linux-arm.tar.gz
          asset_name: modbus2prometheus-linux-arm.tar.gz
          asset_content_type: application/gzip
